#!/bin/bash -l
#PBS -N iPIC-gpu
#PBS -e ${PBS_JOBNAME}.${PBS_JOBID}.err
#PBS -o ${PBS_JOBNAME}.${PBS_JOBID}.out
#PBS -q qgpu
#PBS -l nodes=1:ppn=1:gpu
#PBS -l walltime=00:01:00
#PBS -V

cd $PBS_O_WORKDIR

## Run the code
##nvprof -o profiling.out ./ipic-gpu.e
##cuda-memcheck ./ipic-gpu.e
./ipic-gpu.e
